
/**
 * Google Apps Script for Form: ats_qualifiers
 * Generated by Forms Automation System
 *
 * SETUP INSTRUCTIONS:
 * 1. Copy this code into a new Apps Script project
 * 2. Update the WEBHOOK_URL below to your actual endpoint
 * 3. Save and authorize the script
 * 4. Run setupFormTrigger() once to create the form submit trigger
 * 5. Test with testWebhook() function
 */

// =============================================================================
// CONFIGURATION - UPDATE THESE VALUES
// =============================================================================

const FORM_SOURCE_TAG = 'ats_qualifiers';
const WEBHOOK_URL = 'https://your-webhook-endpoint.com/webhook'; // UPDATE THIS!
const MASTER_SHEET_ID = '1Ux8iEW8dabbEMUq1mEhrpY6a0WAUTCTR_8kvZ-hLHaQ';

// Dropdown values from master sheet
const DROPDOWN_VALUES = {
  "status": [
    "New Parent",
    "Contacted",
    "Follow-up",
    "Enrolled",
    "Not Interested"
  ],
  "interestLevel": [
    "High",
    "Medium",
    "Low"
  ],
  "sourceTag": [
    "returning_students",
    "ats_qualifiers",
    "website",
    "early_bird"
  ],
  "assignedOwner": [
    "Unassigned",
    "Rajesh",
    "Team Member"
  ]
};

// =============================================================================
// MAIN FUNCTIONS
// =============================================================================

/**
 * Main trigger function - runs when form is submitted
 */
function onFormSubmit(e) {
  console.log('📝 Form submission detected for ats_qualifiers');

  try {
    const formResponse = e.response;
    const itemResponses = formResponse.getItemResponses();

    // Build response data object
    const responseData = {
      formId: '1gGyfmy4NmEgAdZrbex0ffoqGlI1B_LuRUfzvQeOCHCQ',
      sourceTag: FORM_SOURCE_TAG,
      timestamp: new Date().toISOString(),
      responseId: formResponse.getId(),
      submissionTime: formResponse.getTimestamp().toISOString()
    };

    // Extract form field values
    itemResponses.forEach(itemResponse => {
      const question = itemResponse.getItem().getTitle();
      const answer = itemResponse.getResponse();
      responseData[question] = answer;
    });

    console.log('📋 Form data collected:', responseData);

    // Send to webhook endpoint
    const webhookPayload = {
      formData: responseData,
      source: 'google-apps-script',
      version: '1.0',
      metadata: {
        formName: 'ats_qualifiers',
        sourceTag: FORM_SOURCE_TAG,
        dropdownValues: DROPDOWN_VALUES
      }
    };

    const webhookResponse = sendToWebhook(webhookPayload);

    if (webhookResponse.success) {
      console.log('✅ Form data sent to webhook successfully');
      updateMasterSheetDirectly(responseData);
    } else {
      console.error('❌ Webhook failed, storing for retry:', webhookResponse.error);
      storeFailedSubmission(responseData, webhookResponse.error);
      // Try direct sheet update as fallback
      updateMasterSheetDirectly(responseData);
    }

  } catch (error) {
    console.error('❌ Error processing form submission:', error.toString());
    storeProcessingError(error.toString(), e);
  }
}

/**
 * Send data to webhook endpoint
 */
function sendToWebhook(payload) {
  try {
    const response = UrlFetchApp.fetch(WEBHOOK_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'User-Agent': 'GoogleAppsScript-FormTrigger/1.0'
      },
      payload: JSON.stringify(payload),
      muteHttpExceptions: true
    });

    const responseCode = response.getResponseCode();
    const responseText = response.getContentText();

    if (responseCode >= 200 && responseCode < 300) {
      return { success: true, response: responseText };
    } else {
      return {
        success: false,
        error: `HTTP ${responseCode}: ${responseText}`
      };
    }
  } catch (error) {
    return {
      success: false,
      error: `Network error: ${error.toString()}`
    };
  }
}

/**
 * Update master sheet directly as backup method
 */
function updateMasterSheetDirectly(responseData) {
  try {
    const sheet = SpreadsheetApp.openById(MASTER_SHEET_ID).getActiveSheet();

    // Map form data to master sheet format based on common field variations
    const mappedData = mapFormFields(responseData);

    const rowData = [
      mappedData.childName || '',
      mappedData.parentName || '',
      mappedData.parentEmail || '',
      mappedData.parentMobile || '',
      mappedData.interestLevel || 'Medium',
      FORM_SOURCE_TAG,
      mappedData.timestamp || new Date().toISOString(),
      'No', // Duplicate Flag
      'New Parent', // Status
      '', // Assigned Owner
      `Auto-added from ${FORM_SOURCE_TAG} on ${new Date().toLocaleDateString()}` // Notes
    ];

    sheet.appendRow(rowData);
    console.log('✅ Data added directly to master sheet');

  } catch (error) {
    console.error('❌ Failed to update master sheet directly:', error.toString());
  }
}

/**
 * Map form fields to standardized format
 */
function mapFormFields(responseData) {
  const mapped = {};

  // Child Name variations
  const childNameFields = ['Child Name', "Child's Name", 'Student Name', 'Name of Child', 'Child Full Name', 'Kid Name', 'Student', 'Learner Name'];
  for (const field of childNameFields) {
    if (responseData[field]) {
      mapped.childName = responseData[field];
      break;
    }
  }

  // Parent Name variations
  const parentNameFields = ['Parent Name', "Parent's Name", 'Guardian Name', "Father's Name", "Mother's Name", 'Parent/Guardian Name', 'Your Name', 'Full Name', 'Guardian', 'Contact Person Name'];
  for (const field of parentNameFields) {
    if (responseData[field]) {
      mapped.parentName = responseData[field];
      break;
    }
  }

  // Email variations
  const emailFields = ['Parent Email', 'Email Address', 'Email', 'Parent Email Address', 'Guardian Email', 'Your Email', 'Contact Email'];
  for (const field of emailFields) {
    if (responseData[field]) {
      mapped.parentEmail = responseData[field];
      break;
    }
  }

  // Mobile variations
  const mobileFields = ['Parent Mobile', 'Mobile Number', 'Phone Number', 'Contact Number', 'Parent Contact', 'Mobile', 'Phone', 'Contact', 'Your Mobile', 'WhatsApp Number'];
  for (const field of mobileFields) {
    if (responseData[field]) {
      mapped.parentMobile = responseData[field];
      break;
    }
  }

  // Interest Level variations
  const interestFields = ['Interest Level', 'Level of Interest', 'How interested are you?', 'Interest', 'Priority', 'How likely are you to enroll?', 'Urgency'];
  for (const field of interestFields) {
    if (responseData[field]) {
      mapped.interestLevel = normalizeInterestLevel(responseData[field]);
      break;
    }
  }

  mapped.timestamp = responseData.timestamp || responseData.Timestamp || responseData['Response Time'] || responseData['Submitted At'];

  return mapped;
}

/**
 * Normalize interest level values
 */
function normalizeInterestLevel(value) {
  const highValues = ['Very High', 'Very Interested', 'High', 'Interested', 'Urgent', 'High Priority', 'Very Likely', 'Definitely', 'Likely', 'Immediate', 'ASAP'];
  const lowValues = ['Low', 'Not Very Interested', 'Maybe', 'Low Priority', 'Unlikely', 'Not Sure', 'Later'];

  if (highValues.includes(value)) return 'High';
  if (lowValues.includes(value)) return 'Low';
  return 'Medium';
}

// =============================================================================
// UTILITY FUNCTIONS
// =============================================================================

/**
 * Store failed submissions for retry
 */
function storeFailedSubmission(responseData, error) {
  try {
    const props = PropertiesService.getScriptProperties();
    const failedSubmissions = JSON.parse(props.getProperty('failedSubmissions') || '[]');

    failedSubmissions.push({
      data: responseData,
      error: error,
      timestamp: new Date().toISOString(),
      retryCount: 0
    });

    props.setProperty('failedSubmissions', JSON.stringify(failedSubmissions));
    console.log('📝 Failed submission stored for retry');

  } catch (error) {
    console.error('❌ Failed to store failed submission:', error.toString());
  }
}

/**
 * Store processing errors for investigation
 */
function storeProcessingError(error, originalEvent) {
  try {
    const props = PropertiesService.getScriptProperties();
    const errors = JSON.parse(props.getProperty('processingErrors') || '[]');

    errors.push({
      error: error,
      timestamp: new Date().toISOString(),
      formSource: FORM_SOURCE_TAG,
      eventData: originalEvent ? originalEvent.toString() : 'No event data'
    });

    if (errors.length > 50) {
      errors.splice(0, errors.length - 50);
    }

    props.setProperty('processingErrors', JSON.stringify(errors));
    console.log('📝 Processing error logged');

  } catch (error) {
    console.error('❌ Failed to store processing error:', error.toString());
  }
}

// =============================================================================
// SETUP AND TESTING FUNCTIONS
// =============================================================================

/**
 * SETUP FUNCTION - Run this once after deploying the script
 */
function setupFormTrigger() {
  try {
    console.log('⚡ Setting up form submit trigger for ats_qualifiers...');

    // Delete existing triggers to avoid duplicates
    const triggers = ScriptApp.getProjectTriggers();
    triggers.forEach(trigger => {
      if (trigger.getHandlerFunction() === 'onFormSubmit') {
        ScriptApp.deleteTrigger(trigger);
      }
    });

    // Create new form submit trigger
    const trigger = ScriptApp.newTrigger('onFormSubmit')
      .onFormSubmit()
      .create();

    console.log('✅ Form submit trigger created successfully');
    console.log('📋 Trigger ID:', trigger.getUniqueId());

    return trigger.getUniqueId();

  } catch (error) {
    console.error('❌ Failed to setup form trigger:', error.toString());
    throw error;
  }
}

/**
 * TEST FUNCTION - Test webhook connectivity
 */
function testWebhook() {
  console.log('🧪 Testing webhook connectivity...');

  const testPayload = {
    formData: {
      'Child Name': 'Test Child',
      'Parent Name': 'Test Parent',
      'Parent Email': 'test@example.com',
      'Parent Mobile': '+1234567890',
      'Interest Level': 'High',
      formId: '1gGyfmy4NmEgAdZrbex0ffoqGlI1B_LuRUfzvQeOCHCQ',
      sourceTag: FORM_SOURCE_TAG,
      timestamp: new Date().toISOString(),
      responseId: 'test-response-' + Date.now(),
      submissionTime: new Date().toISOString()
    },
    source: 'google-apps-script-test',
    version: '1.0',
    metadata: {
      formName: 'ats_qualifiers',
      sourceTag: FORM_SOURCE_TAG,
      testRun: true
    }
  };

  const result = sendToWebhook(testPayload);

  if (result.success) {
    console.log('✅ Webhook test successful:', result.response);
  } else {
    console.error('❌ Webhook test failed:', result.error);
    console.log('ℹ️ Testing direct sheet update as fallback...');
    updateMasterSheetDirectly(testPayload.formData);
  }

  return result;
}

/**
 * Get status and diagnostics
 */
function getStatus() {
  try {
    const props = PropertiesService.getScriptProperties();
    const failedSubmissions = JSON.parse(props.getProperty('failedSubmissions') || '[]');
    const errors = JSON.parse(props.getProperty('processingErrors') || '[]');

    const status = {
      formName: 'ats_qualifiers',
      sourceTag: FORM_SOURCE_TAG,
      webhookUrl: WEBHOOK_URL,
      masterSheetId: MASTER_SHEET_ID,
      failedSubmissions: failedSubmissions.length,
      processingErrors: errors.length,
      lastCheck: new Date().toISOString(),
      dropdownValues: DROPDOWN_VALUES
    };

    console.log('📊 Form Status:', JSON.stringify(status, null, 2));
    return status;

  } catch (error) {
    console.error('❌ Error getting status:', error.toString());
    return { error: error.toString() };
  }
}

/**
 * Manual retry function for failed submissions
 */
function retryFailedSubmissions() {
  try {
    const props = PropertiesService.getScriptProperties();
    const failedSubmissions = JSON.parse(props.getProperty('failedSubmissions') || '[]');

    if (failedSubmissions.length === 0) {
      console.log('ℹ️ No failed submissions to retry');
      return;
    }

    console.log(`🔄 Retrying ${failedSubmissions.length} failed submissions...`);

    const successfulRetries = [];
    const stillFailing = [];

    failedSubmissions.forEach((submission, index) => {
      if (submission.retryCount >= 3) {
        stillFailing.push(submission);
        return;
      }

      const webhookPayload = {
        formData: submission.data,
        source: 'google-apps-script-retry',
        version: '1.0',
        metadata: {
          formName: 'ats_qualifiers',
          sourceTag: FORM_SOURCE_TAG,
          retryAttempt: submission.retryCount + 1,
          originalError: submission.error
        }
      };

      const result = sendToWebhook(webhookPayload);

      if (result.success) {
        successfulRetries.push(index);
        console.log(`✅ Retry successful for submission ${index}`);
      } else {
        submission.retryCount += 1;
        submission.lastRetryError = result.error;
        submission.lastRetryTime = new Date().toISOString();
        stillFailing.push(submission);
        console.log(`❌ Retry failed for submission ${index}: ${result.error}`);
      }
    });

    props.setProperty('failedSubmissions', JSON.stringify(stillFailing));

    console.log(`🎯 Retry complete: ${successfulRetries.length} successful, ${stillFailing.length} still failing`);

  } catch (error) {
    console.error('❌ Error during retry process:', error.toString());
  }
}

// =============================================================================
// INSTRUCTIONS
// =============================================================================

/**
 * DEPLOYMENT INSTRUCTIONS
 *
 * 1. Copy this entire code
 * 2. Go to Google Apps Script: https://script.google.com/
 * 3. Create a new project
 * 4. Replace the default code with this code
 * 5. Update WEBHOOK_URL in the configuration section
 * 6. Save the project with name: "ats_qualifiers Automation"
 * 7. Run setupFormTrigger() once to create the trigger
 * 8. Test with testWebhook() function
 * 9. Check getStatus() for monitoring
 *
 * Your form will now automatically send data to the webhook and master sheet!
 */
